export const enum CiseServiceType {
  VESSEL_DOCUMENT_SERVICE = 'VESSEL_DOCUMENT_SERVICE',
  ORGANIZATION_DOCUMENT_SERVICE = 'ORGANIZATION_DOCUMENT_SERVICE',
  AIRCRAFT_SERVICE = 'AIRCRAFT_SERVICE',
  VESSEL_SERVICE = 'VESSEL_SERVICE',
  DOCUMENT_SERVICE = 'DOCUMENT_SERVICE',
  OPERATIONAL_ASSET_SERVICE = 'OPERATIONAL_ASSET_SERVICE',
  MOVEMENT_SERVICE = 'MOVEMENT_SERVICE',
  ACTION_SERVICE = 'ACTION_SERVICE',
  MARITIME_SAFETY_INCIDENT_SERVICE = 'MARITIME_SAFETY_INCIDENT_SERVICE',
  LAND_VEHICLE_SERVICE = 'LAND_VEHICLE_SERVICE',
  EVENT_DOCUMENT_SERVICE = 'EVENT_DOCUMENT_SERVICE',
  RISK_SERVICE = 'RISK_SERVICE',
  LAW_INFRINGEMENT_INCIDENT_SERVICE = 'LAW_INFRINGEMENT_INCIDENT_SERVICE',
  PERSON_SERVICE = 'PERSON_SERVICE',
  LOCATION_SERVICE = 'LOCATION_SERVICE',
  METEO_OCEANOGRAPHIC_OBSERVATION_SERVICE = 'METEO_OCEANOGRAPHIC_OBSERVATION_SERVICE',
  CERTIFICATE_DOCUMENT_SERVICE = 'CERTIFICATE_DOCUMENT_SERVICE',
  AGENT_SERVICE = 'AGENT_SERVICE',
  INCIDENT_SERVICE = 'INCIDENT_SERVICE',
  LOCATION_DOCUMENT_SERVICE = 'LOCATION_DOCUMENT_SERVICE',
  ANOMALY_SERVICE = 'ANOMALY_SERVICE',
  IRREGULAR_MIGRATION_INCIDENT_SERVICE = 'IRREGULAR_MIGRATION_INCIDENT_SERVICE',
  CARGO_SERVICE = 'CARGO_SERVICE',
  RISK_DOCUMENT_SERVICE = 'RISK_DOCUMENT_SERVICE',
  PERSON_DOCUMENT_SERVICE = 'PERSON_DOCUMENT_SERVICE',
  CARGO_DOCUMENT_SERVICE = 'CARGO_DOCUMENT_SERVICE',
  CRISIS_INCIDENT_SERVICE = 'CRISIS_INCIDENT_SERVICE',
  ORGANIZATION_SERVICE = 'ORGANIZATION_SERVICE'
}

export const enum CiseServiceOperationType {
  PUSH = 'PUSH',
  SUBSCRIBE = 'SUBSCRIBE',
  ACKNOWLEDGEMENT = 'ACKNOWLEDGEMENT',
  FEEDBACK = 'FEEDBACK',
  PULL = 'PULL'
}

export interface ICiseService {
  id?: number;
  name?: string;
  serviceType?: CiseServiceType;
  serviceOperation?: CiseServiceOperationType;
  ciseRuleSetId?: number;
  ciseAuthorityId?: number;
}

export const defaultValue: Readonly<ICiseService> = {};
