export const enum CiseCommunityType {
  FISHERIES_CONTROL = 'FISHERIES_CONTROL',
  GENERAL_LAW_ENFORCEMENT = 'GENERAL_LAW_ENFORCEMENT',
  CUSTOMS = 'CUSTOMS',
  MARITIME_SAFETY_SECURITY = 'MARITIME_SAFETY_SECURITY',
  NON_SPECIFIED = 'NON_SPECIFIED',
  MARINE_ENVIRONMENT = 'MARINE_ENVIRONMENT',
  OTHER = 'OTHER',
  BORDER_CONTROL = 'BORDER_CONTROL',
  DEFENCE_MONITORING = 'DEFENCE_MONITORING'
}

export const enum CiseDataFreshnessType {
  REAL_TIME = 'REAL_TIME',
  NEARLY_REAL_TIME = 'NEARLY_REAL_TIME',
  UNKNOWN = 'UNKNOWN',
  HISTORIC = 'HISTORIC'
}

export const enum CiseFunctionType {
  LAW_ENFORCEMENT_MONITORING = 'LAW_ENFORCEMENT_MONITORING',
  NON_SPECIFIED = 'NON_SPECIFIED',
  CUSTOMS_OPERATION = 'CUSTOMS_OPERATION',
  BORDER_OPERATION = 'BORDER_OPERATION',
  BORDER_MONITORING = 'BORDER_MONITORING',
  ENVIRONMENT_MONITORING = 'ENVIRONMENT_MONITORING',
  CUSTOMS_MONITORING = 'CUSTOMS_MONITORING',
  ENVIRONMENT_WARNING = 'ENVIRONMENT_WARNING',
  CSDP_TASK = 'CSDP_TASK',
  COUNTER_TERRORISM = 'COUNTER_TERRORISM',
  LAW_ENFORCEMENT_OPERATION = 'LAW_ENFORCEMENT_OPERATION',
  OPERATION = 'OPERATION',
  FISHERIES_WARNING = 'FISHERIES_WARNING',
  FISHERIES_OPERATION = 'FISHERIES_OPERATION',
  VTM = 'VTM',
  SAFETY = 'SAFETY',
  SECURITY = 'SECURITY',
  FISHERIES_MONITORING = 'FISHERIES_MONITORING',
  DEFENCE_MONITORING = 'DEFENCE_MONITORING',
  SAR = 'SAR',
  ENVIRONMENT_RESPONSE = 'ENVIRONMENT_RESPONSE'
}

export const enum CiseSeaBasinType {
  ATLANTIC = 'ATLANTIC',
  ARCTIC_OCEAN = 'ARCTIC_OCEAN',
  NON_SPECIFIED = 'NON_SPECIFIED',
  BALTIC_SEA = 'BALTIC_SEA',
  OUTERMOST_REGIONS = 'OUTERMOST_REGIONS',
  NORTH_SEA = 'NORTH_SEA',
  MEDITERRANEAN = 'MEDITERRANEAN',
  BLACK_SEA = 'BLACK_SEA'
}

export const enum CiseServiceRoleType {
  CONSUMER = 'CONSUMER',
  PROVIDER = 'PROVIDER'
}

export const enum CiseServiceType {
  VESSEL_DOCUMENT_SERVICE = 'VESSEL_DOCUMENT_SERVICE',
  ORGANIZATION_DOCUMENT_SERVICE = 'ORGANIZATION_DOCUMENT_SERVICE',
  AIRCRAFT_SERVICE = 'AIRCRAFT_SERVICE',
  VESSEL_SERVICE = 'VESSEL_SERVICE',
  DOCUMENT_SERVICE = 'DOCUMENT_SERVICE',
  OPERATIONAL_ASSET_SERVICE = 'OPERATIONAL_ASSET_SERVICE',
  MOVEMENT_SERVICE = 'MOVEMENT_SERVICE',
  ACTION_SERVICE = 'ACTION_SERVICE',
  MARITIME_SAFETY_INCIDENT_SERVICE = 'MARITIME_SAFETY_INCIDENT_SERVICE',
  LAND_VEHICLE_SERVICE = 'LAND_VEHICLE_SERVICE',
  EVENT_DOCUMENT_SERVICE = 'EVENT_DOCUMENT_SERVICE',
  RISK_SERVICE = 'RISK_SERVICE',
  LAW_INFRINGEMENT_INCIDENT_SERVICE = 'LAW_INFRINGEMENT_INCIDENT_SERVICE',
  PERSON_SERVICE = 'PERSON_SERVICE',
  LOCATION_SERVICE = 'LOCATION_SERVICE',
  METEO_OCEANOGRAPHIC_OBSERVATION_SERVICE = 'METEO_OCEANOGRAPHIC_OBSERVATION_SERVICE',
  CERTIFICATE_DOCUMENT_SERVICE = 'CERTIFICATE_DOCUMENT_SERVICE',
  AGENT_SERVICE = 'AGENT_SERVICE',
  INCIDENT_SERVICE = 'INCIDENT_SERVICE',
  LOCATION_DOCUMENT_SERVICE = 'LOCATION_DOCUMENT_SERVICE',
  ANOMALY_SERVICE = 'ANOMALY_SERVICE',
  IRREGULAR_MIGRATION_INCIDENT_SERVICE = 'IRREGULAR_MIGRATION_INCIDENT_SERVICE',
  CARGO_SERVICE = 'CARGO_SERVICE',
  RISK_DOCUMENT_SERVICE = 'RISK_DOCUMENT_SERVICE',
  PERSON_DOCUMENT_SERVICE = 'PERSON_DOCUMENT_SERVICE',
  CARGO_DOCUMENT_SERVICE = 'CARGO_DOCUMENT_SERVICE',
  CRISIS_INCIDENT_SERVICE = 'CRISIS_INCIDENT_SERVICE',
  ORGANIZATION_SERVICE = 'ORGANIZATION_SERVICE'
}

export interface ICiseServiceProfile {
  id?: number;
  name?: string;
  serviceId?: string;
  community?: CiseCommunityType;
  country?: string;
  dataFreshness?: CiseDataFreshnessType;
  serviceFunction?: CiseFunctionType;
  seaBasin?: CiseSeaBasinType;
  serviceRole?: CiseServiceRoleType;
  serviceType?: CiseServiceType;
  ciseRuleId?: number;
}

export const defaultValue: Readonly<ICiseServiceProfile> = {};
