package eu.cise.console.domain.enumeration;

/**
 * The CiseFunctionType enumeration.
 */
public enum CiseFunctionType {
    LAW_ENFORCEMENT_MONITORING, NON_SPECIFIED, CUSTOMS_OPERATION, BORDER_OPERATION, BORDER_MONITORING, ENVIRONMENT_MONITORING, CUSTOMS_MONITORING, ENVIRONMENT_WARNING, CSDP_TASK, COUNTER_TERRORISM, LAW_ENFORCEMENT_OPERATION, OPERATION, FISHERIES_WARNING, FISHERIES_OPERATION, VTM, SAFETY, SECURITY, FISHERIES_MONITORING, DEFENCE_MONITORING, SAR, ENVIRONMENT_RESPONSE
}
